DICT_WMO_RELATIVELY_COLS_ALL = {'aantalinwoners': ['geboorterelatief',
                                                   'alleenstaande_totaal_mannen_en_vrouwen',
                                                   'personenpersoortuitkeringao',
                                                   'ouder_in_eenouderhuishouden_totaal_mannen_en_vrouwen',
                                                   'overignietwesters',
                                                   'mannen',
                                                   'k25tot45jaar',
                                                   'suriname',
                                                   'verweduwd',
                                                   'overig_lid_huishouden_mannen',
                                                   'alleenstaande_vrouwen',
                                                   'gehuwd',
                                                   'nederlandseantillenenaruba',
                                                   'personenpersoortuitkeringww',
                                                   'gescheiden',
                                                   'k65jaarofouder',
                                                   'aantalinkomensontvangers',
                                                   'k0tot15jaar',
                                                   'vrouwen',
                                                   'nietwesterstotaal',
                                                   'alleenstaande_mannen',
                                                   'overig_lid_huishouden_vrouwen',
                                                   'overig_lid_huishouden_totaal_mannen_en_vrouwen',
                                                   'personenpersoortuitkeringaow',
                                                   'geboortetotaal',
                                                   'k45tot65jaar',
                                                   'sterfterelatief',
                                                   'personenpersoortuitkeringbijstand',
                                                   'ongehuwd',
                                                   'ouder_in_eenouderhuishouden_vrouwen',
                                                   'sterftetotaal',
                                                   'turkije',
                                                   'ouder_in_eenouderhuishouden_mannen',
                                                   'k15tot25jaar',
                                                   'percentagewmoclienten',
                                                   'westerstotaal',
                                                   'marokko'],
                                'huishoudenstotaal': ['eenpersoonshuishoudens',
                                                      'huishoudenszonderkinderen',
                                                      'huishoudensmetkinderen'],
                                'bedrijfsvestigingentotaal': ['alandbouwbosbouwenvisserij',
                                                              'bfnijverheidenenergie',
                                                              'gihandelenhoreca',
                                                              'hjvervoerinformatieencommunicatie',
                                                              'klfinancieledienstenonroerendgoed',
                                                              'mnzakelijkedienstverlening',
                                                              'rucultuurrecreatieoverigediensten'],
                                'personenautostotaal': ['personenautosbrandstofbenzine',
                                                        'personenautosoverigebrandstof'],
                                'oppervlaktetotaal': ['oppervlakteland', 'oppervlaktewater'],
                                'poptotalebevolking': ['popmannen',
                                                       'popvrouwen',
                                                       'popjongerdan5jaarleeftijdsgroep',
                                                       'popk5tot10jaarleeftijdsgroep',
                                                       'popk10tot15jaarleeftijdsgroep',
                                                       'popk15tot20jaarleeftijdsgroep',
                                                       'popk20tot25jaarleeftijdsgroep',
                                                       'popk25tot45jaarleeftijdsgroep',
                                                       'popk45tot65jaarleeftijdsgroep',
                                                       'popk65tot80jaarleeftijdsgroep',
                                                       'popk80jaarofouderleeftijdsgroep',
                                                       'popongehuwdtot',
                                                       'popgehuwdtot',
                                                       'popgescheidentot',
                                                       'popverweduwdtot',
                                                       'popinwoners15jaarofouder',
                                                       'popnederlandseachtergrond',
                                                       'poptotaalmetmigratieachtergrond',
                                                       'popwestersemigratieachtergrond',
                                                       'poptotaalnietwestersemigratieachtergrond',
                                                       'popmarokko',
                                                       'popvoormaligenederlandseantillenaruba',
                                                       'popsuriname',
                                                       'popturkije',
                                                       'popoverignietwestersemigratieachtergrond',
                                                       'popzeersterkstedelijk',
                                                       'popsterkstedelijk',
                                                       'popmatigstedelijk',
                                                       'popweinigstedelijk',
                                                       'popnietstedelijk',
                                                       'popgeboorte',
                                                       'popsterfte',
                                                       'popgeboorteoverschot',
                                                       'popnieuwvormingen',
                                                       'popziektenvanhartenvaatstelsel',
                                                       'popziektenvanademhalingsstelsel',
                                                       'popuitwendigedoodsoorzaken',
                                                       'popoverigedoodsoorzaken',
                                                       'popvestiginguitanderegemeente',
                                                       'popvertreknaaranderegemeente',
                                                       'popbinnenlandsmigratiesaldo',
                                                       'popbinnenlandsmigratiesaldorelatief',
                                                       'popverhuismobiliteitrelatief',
                                                       'popimmigratie',
                                                       'popemigratie',
                                                       'popmigratiesaldo',
                                                       'popinwonersop31december',
                                                       'popbevolkingsgroei',
                                                       'popgemiddeldaantalinwoners',
                                                       'popbasisonderwijs',
                                                       'popspeciaalbasisonderwijs',
                                                       'popspecialescholen',
                                                       'popvoortgezetonderwijs',
                                                       'popberoepsopleidendeleerweg',
                                                       'popberoepsbegeleidendeleerweg',
                                                       'pophogerberoepsonderwijs',
                                                       'popwetenschappelijkonderwijs',
                                                       'popvoortgezetonderwijsdiploma',
                                                       'popmiddelbaarberoepsonderwijs',
                                                       'pophogerberoepsonderwijsbachelor',
                                                       'popwomasterdoctoraal',
                                                       'poptotaalaantalbanen',
                                                       'popalandbouwbosbouwenvisserijbanen',
                                                       'popbfnijverheidenenergiebanen',
                                                       'popgncommercieledienstverleningbanen',
                                                       'popounietcommercieledienstverleningbanen',
                                                       'popakkerbouw',
                                                       'poptuinbouwopengrond',
                                                       'poptuinbouwonderglas',
                                                       'popblijvendgrasland',
                                                       'popnatuurlijkgrasland',
                                                       'poptijdelijkgrasland',
                                                       'popgroenvoedergewassen',
                                                       'popstikstofuitscheiding',
                                                       'popfosfaatuitscheiding',
                                                       'popkaliuitscheiding',
                                                       'popdunnemest',
                                                       'popvastemest',
                                                       'poppersonenautos',
                                                       'poppersonenautosparticulieren',
                                                       'popbedrijfsmotorvoertuigen',
                                                       'popmotorfietsen',
                                                       'popvoertuigenmetbromfietskenteken',
                                                       'poptotaalhuishoudelijkafval',
                                                       'pophuishoudelijkrestafval',
                                                       'popgrofhuishoudelijkrestafval',
                                                       'popgftafval',
                                                       'popoudpapierenkarton',
                                                       'popverpakkingsglas',
                                                       'poptextiel',
                                                       'popkleinchemischafval',
                                                       'popoverighuishoudelijkafval',
                                                       'poptotaleoppervlakte',
                                                       'popland',
                                                       'popwatertotaal',
                                                       'popbinnenwater',
                                                       'popbuitenwater',
                                                       'popomgevingsadressendichtheid',
                                                       'popverkeersterreinopp',
                                                       'popbebouwdterreinopp',
                                                       'popsemibebouwdterreinopp',
                                                       'poprecreatieterreinopp',
                                                       'popagrarischterreinopp',
                                                       'popbosenopennatuurlijkterreinopp'],
                                'poptotaledruk': ['popgroenedruk', 'popgrijzedruk'],
                                'popinwoners15jaarofouder': ['popongehuwdouderdan14',
                                                             'popgehuwdouderdan14',
                                                             'popgescheidenouderdan14',
                                                             'popverweduwdouderdan14'],
                                'poptotaalaantalparticulierehuishoudens': ['popeenpersoonshuishoudens',
                                                                           'pophuishoudenszonderkinderen',
                                                                           'pophuishoudensmetkinderen',
                                                                           'popeenpersoonshuishoudensrelatief',
                                                                           'pophuishoudenszonderkinderenrelatief',
                                                                           'pophuishoudensmetkinderenrelatief',
                                                                           'popgemiddeldehuishoudensgrootte',
                                                                           'popvoorraadop1januari',
                                                                           'popnieuwbouwwoningen',
                                                                           'popsaldovermeerderingwoningenrelatief',
                                                                           'popwoningdichtheid',
                                                                           'popkoopwoningen',
                                                                           'pophuurwoningen',
                                                                           'popeigendomonbekend',
                                                                           'popwoningen',
                                                                           'popnietwoningen',
                                                                           'popgemiddeldewoningwaarde'],
                                'popbedrijfsvestigingentotaal': ['popalandbouwbosbouwenvisserij',
                                                                 'popbfnijverheidenenergie',
                                                                 'popgihandelenhoreca',
                                                                 'pophjvervoerinformatieencommunicatie',
                                                                 'popklfinancieledienstenonroerendgoed',
                                                                 'popmnzakelijkedienstverlening',
                                                                 'poprucultuurrecreatieoverigediensten'],
                                'poptotaleweglengte': ['popgemeentelijkeenwaterschapswegen',
                                                       'popprovincialewegen',
                                                       'poprijkswegen']}
LIST_WMO_GET_DATA_ALL = ['perioden',
                         'typemaatwerkarrangement',
                         'aantalinkomensontvangers',
                         'aantalinwoners',
                         'actieven1575jaar',
                         'afstandtotgrotesupermarkt',
                         'afstandtothuisartsenpraktijk',
                         'afstandtotkinderdagverblijf',
                         'afstandtotschool',
                         'alandbouwbosbouwenvisserij',
                         'bedrijfsmotorvoertuigen',
                         'bedrijfsvestigingentotaal',
                         'bevolkingsdichtheid',
                         'bfnijverheidenenergie',
                         'bouwjaarvanaf2000',
                         'bouwjaarvoor2000',
                         'dekkingspercentage',
                         'eenpersoonshuishoudens',
                         'eigendomonbekend',
                         'geboorterelatief',
                         'geboortetotaal',
                         'gehuwd',
                         'gemeentenaam',
                         'gemelectriciteitsverbruikappartement',
                         'gemelectriciteitsverbruikeigenwoning',
                         'gemelectriciteitsverbruikhoekwoning',
                         'gemelectriciteitsverbruikhuurwoning',
                         'gemelectriciteitsverbruiktussenwoning',
                         'gemelectriciteitsverbruiktweeondereenkapwoning',
                         'gemelectriciteitsverbruikvrijstaandewoning',
                         'gemgasverbruikappartement',
                         'gemgasverbruikeigenwoning',
                         'gemgasverbruikhoekwoning',
                         'gemgasverbruikhuurwoning',
                         'gemgasverbruiktussenwoning',
                         'gemgasverbruiktweeondereenkapwoning',
                         'gemgasverbruikvrijstaandewoning',
                         'gemgestandaardiseerdinkomenvanhuish',
                         'gemiddeldaardgasverbruiktotaal',
                         'gemiddeldehuishoudensgrootte',
                         'gemiddeldelektriciteitsverbruiktotaal',
                         'gemiddeldewoningwaarde',
                         'gemiddeldinkomenperinkomensontvanger',
                         'gemiddeldinkomenperinwoner',
                         'gescheiden',
                         'geweldsenseksuelemisdrijven',
                         'gihandelenhoreca',
                         'hjvervoerinformatieencommunicatie',
                         'huishonderofrondsociaalminimum',
                         'huishoudensmeteenlaaginkomen',
                         'huishoudensmetkinderen',
                         'huishoudenstot110vansociaalminimum',
                         'huishoudenstot120vansociaalminimum',
                         'huishoudenstotaal',
                         'huishoudenszonderkinderen',
                         'huurwoningentotaal',
                         'inbezitoverigeverhuurders',
                         'inbezitwoningcorporatie',
                         'jongerenmetjeugdzorginnatura',
                         'k0tot15jaar',
                         'k15tot25jaar',
                         'k20huishoudensmethoogsteinkomen',
                         'k20personenmethoogsteinkomen',
                         'k25tot45jaar',
                         'k40huishoudensmetlaagsteinkomen',
                         'k40personenmetlaagsteinkomen',
                         'k45tot65jaar',
                         'k65jaarofouder',
                         'klfinancieledienstenonroerendgoed',
                         'koopwoningen',
                         'mannen',
                         'marokko',
                         'matevanstedelijkheid',
                         'mediaanvermogenvanparticulierehuish',
                         'meestvoorkomendepostcode',
                         'mnzakelijkedienstverlening',
                         'motorfietsen',
                         'nederlandseantillenenaruba',
                         'nettoarbeidsparticipatie',
                         'nietwesterstotaal',
                         'omgevingsadressendichtheid',
                         'ongehuwd',
                         'opleidingsniveauhoog',
                         'opleidingsniveaulaag',
                         'opleidingsniveaumiddelbaar',
                         'oppervlakteland',
                         'oppervlaktetotaal',
                         'oppervlaktewater',
                         'overignietwesters',
                         'percentagebewoond',
                         'percentageeengezinswoning',
                         'percentagejongerenmetjeugdzorg',
                         'percentagemeergezinswoning',
                         'percentageonbewoond',
                         'percentagewerknemers',
                         'percentagewoningenmetstadsverwarming',
                         'percentagezelfstandigen',
                         'personenautos6jaarenouder',
                         'personenautosbrandstofbenzine',
                         'personenautosjongerdan6jaar',
                         'personenautosnaaroppervlakte',
                         'personenautosoverigebrandstof',
                         'personenautosperhuishouden',
                         'personenautostotaal',
                         'personenpersoortuitkeringao',
                         'personenpersoortuitkeringaow',
                         'personenpersoortuitkeringbijstand',
                         'personenpersoortuitkeringww',
                         'rucultuurrecreatieoverigediensten',
                         'scholenbinnen3km',
                         'sterfterelatief',
                         'sterftetotaal',
                         'suriname',
                         'totaaldiefstaluitwoningschuured',
                         'turkije',
                         'vernielingmisdrijftegenopenbareorde',
                         'verweduwd',
                         'vrouwen',
                         'westerstotaal',
                         'woningvoorraad',
                         'alleenstaande_mannen',
                         'alleenstaande_totaal_mannen_en_vrouwen',
                         'alleenstaande_vrouwen',
                         'ouder_in_eenouderhuishouden_mannen',
                         'ouder_in_eenouderhuishouden_totaal_mannen_en_vrouwen',
                         'ouder_in_eenouderhuishouden_vrouwen',
                         'overig_lid_huishouden_mannen',
                         'overig_lid_huishouden_totaal_mannen_en_vrouwen',
                         'overig_lid_huishouden_vrouwen',
                         'partner_in_paar,_geen_kind(eren)_mannen',
                         'partner_in_paar,_geen_kind(eren)_totaal_mannen_en_vrouwen',
                         'partner_in_paar,_geen_kind(eren)_vrouwen',
                         'partner_in_paar_met_kind(eren)_mannen',
                         'partner_in_paar_met_kind(eren)_totaal_mannen_en_vrouwen',
                         'partner_in_paar_met_kind(eren)_vrouwen',
                         'persoon_in_institutioneel_huishouden_mannen',
                         'persoon_in_institutioneel_huishouden_totaal_mannen_en_vrouwen',
                         'persoon_in_institutioneel_huishouden_vrouwen',
                         'persoon_in_particulier_huishouden_mannen',
                         'persoon_in_particulier_huishouden_totaal_mannen_en_vrouwen',
                         'persoon_in_particulier_huishouden_vrouwen',
                         'thuiswonend_kind_mannen',
                         'thuiswonend_kind_totaal_mannen_en_vrouwen',
                         'thuiswonend_kind_vrouwen',
                         'totaal_personen_mannen',
                         'totaal_personen_totaal_mannen_en_vrouwen',
                         'totaal_personen_vrouwen',
                         'popaantalbasisonderwijsscholenbinnen3km',
                         'popaantalbioscopenbinnen10km',
                         'popaantalgrotesupermarktenbinnen3km',
                         'popaantalhuisartsenpraktijkenbinnen3km',
                         'popaantalkinderdagverblijvenbinnen3km',
                         'popaantalrestaurantsbinnen3km',
                         'popaantalscholenhavovwobinnen5km',
                         'popaantalscholenvmbobinnen5km',
                         'popaantalziekenhuizenbinnen20km',
                         'popafstandtotbibliotheek',
                         'popafstandtotbioscoop',
                         'popafstandtotgrotesupermarkt',
                         'popafstandtothuisartsenpost',
                         'popafstandtothuisartsenpraktijk',
                         'popafstandtotkinderdagverblijf',
                         'popafstandtotopenbaargroen',
                         'popafstandtotoprithoofdverkeersweg',
                         'popafstandtotrestaurant',
                         'popafstandtotschoolbasisonderwijs',
                         'popafstandtotschoolhavovwo',
                         'popafstandtotschoolvmbo',
                         'popafstandtotsportterrein',
                         'popafstandtottreinstation',
                         'popafstandtotziekenhuis',
                         'popafstandtotzwembad',
                         'popagrarischterreinopp',
                         'popagrarischterreinperc',
                         'popagrarischterreinperinwoner',
                         'popakkerbouw',
                         'popalandbouwbosbouwenvisserij',
                         'popalandbouwbosbouwenvisserijbanen',
                         'popalandbouwbosbouwenvisserijbanenrelatief',
                         'popaow',
                         'poparbeidsongeschiktheidtotaal',
                         'popbasisonderwijs',
                         'popbebouwdterreinopp',
                         'popbebouwdterreinperc',
                         'popbebouwdterreinperinwoner',
                         'popbedrijfsmotorvoertuigen',
                         'popbedrijfsvestigingentotaal',
                         'popberoepsbegeleidendeleerweg',
                         'popberoepsopleidendeleerweg',
                         'popbevolkingsdichtheid',
                         'popbevolkingsgroei',
                         'popbevolkingsgroeirelatief',
                         'popbfnijverheidenenergie',
                         'popbfnijverheidenenergiebanen',
                         'popbfnijverheidenenergiebanenrelatief',
                         'popbijstandgerelateerdtotaowleeftijd',
                         'popbijstandgerelateerdvanafaowleeftijd',
                         'popbijstandtotdeaowleeftijd',
                         'popbinnenlandsmigratiesaldo',
                         'popbinnenlandsmigratiesaldorelatief',
                         'popbinnenwater',
                         'popblijvendgrasland',
                         'popbosenopennatuurlijkterreinopp',
                         'popbosenopennatuurlijkterreinperc',
                         'popbosenopennatuurlijkterreinperinwoner',
                         'popbroninkomenalswerknemergembestinkomen',
                         'popbroninkomenalswerknemergemgestandaardinkomen',
                         'popbroninkomenalswerknemermediaaninkomen',
                         'popbroninkomenalszelfstandigegembestinkomen',
                         'popbroninkomenalszelfstandigegemgestandaardinkomen',
                         'popbroninkomenalszelfstandigemediaaninkomen',
                         'popbronoverdrachtsinkomengembestinkomen',
                         'popbronoverdrachtsinkomengemgestandaardinkomen',
                         'popbronoverdrachtsinkomenmediaaninkomen',
                         'popbuitenwater',
                         'popbuurten',
                         'popcodea',
                         'popcodeb',
                         'popcodec',
                         'popcoded',
                         'popcodee',
                         'popcodef',
                         'popcodeg',
                         'popcodeh',
                         'popcodei',
                         'popcodej',
                         'popcodek',
                         'popcodel',
                         'popcodem',
                         'popcoden',
                         'popcodeo',
                         'popcodep',
                         'popcodeq',
                         'popcoder',
                         'popdunnemest',
                         'popedelpelsdieren',
                         'popeenpersoonshuishoudens',
                         'popeenpersoonshuishoudensrelatief',
                         'popeigendomonbekend',
                         'popemigratie',
                         'popfosfaatuitscheiding',
                         'popgeboorte',
                         'popgeboorteoverschot',
                         'popgeboorteoverschotrelatief',
                         'popgeboorterelatief',
                         'popgehuwdouderdan',
                         'popgehuwdtot',
                         'popgeiten',
                         'popgemeentelijkeenwaterschapswegen',
                         'popgemeenten',
                         'popgemiddeldaantalinwoners',
                         'popgemiddeldehuishoudensgrootte',
                         'popgemiddeldewoningwaarde',
                         'popgescheidenouderdan',
                         'popgescheidentot',
                         'popgftafval',
                         'popgihandelenhoreca',
                         'popgncommercieledienstverleningbanen',
                         'popgncommercieledienstverleningbanenrelatief',
                         'popgrijzedruk',
                         'popgroenedruk',
                         'popgroenvoedergewassen',
                         'popgrofhuishoudelijkrestafval',
                         'pophjvervoerinformatieencommunicatie',
                         'pophogerberoepsonderwijs',
                         'pophogerberoepsonderwijsbachelor',
                         'pophuishoudelijkrestafval',
                         'pophuishoudensmetkinderen',
                         'pophuishoudensmetkinderenrelatief',
                         'pophuishoudenszonderkinderen',
                         'pophuishoudenszonderkinderenrelatief',
                         'pophuurwoningen',
                         'popid',
                         'popimmigratie',
                         'popinwoners15jaarofouder',
                         'popinwonersop31december',
                         'popjongerdan5jaarleeftijdsgroep',
                         'popjongerdan5jaarrelatieveleeftijdsgroep',
                         'popk10tot15jaarleeftijdsgroep',
                         'popk10tot15jaarrelatieveleeftijdsgroep',
                         'popk15tot20jaarleeftijdsgroep',
                         'popk15tot20jaarrelatieveleeftijdsgroep',
                         'popk20tot25jaarleeftijdsgroep',
                         'popk20tot25jaarrelatieveleeftijdsgroep',
                         'popk25tot45jaarleeftijdsgroep',
                         'popk25tot45jaarrelatieveleeftijdsgroep',
                         'popk45tot65jaarleeftijdsgroep',
                         'popk45tot65jaarrelatieveleeftijdsgroep',
                         'popk5tot10jaarleeftijdsgroep',
                         'popk5tot10jaarrelatieveleeftijdsgroep',
                         'popk65tot80jaarleeftijdsgroep',
                         'popk65tot80jaarrelatieveleeftijdsgroep',
                         'popk80jaarofouderleeftijdsgroep',
                         'popk80jaarofouderrelatieveleeftijdsgroep',
                         'popkaliuitscheiding',
                         'popkalkoenen',
                         'popkippen',
                         'popkleinchemischafval',
                         'popklfinancieledienstenonroerendgoed',
                         'popkonijnen',
                         'popkoopwoningen',
                         'popkoppelvariabeleregiocode',
                         'popland',
                         'popmannen',
                         'popmarokko',
                         'popmarokkorelatief',
                         'popmatigstedelijk',
                         'popmiddelbaarberoepsonderwijs',
                         'popmigratiesaldo',
                         'popmigratiesaldorelatief',
                         'popmnzakelijkedienstverlening',
                         'popmotorfietsen',
                         'popmotorfietsenrelatief',
                         'popnaama',
                         'popnaamb',
                         'popnaamc',
                         'popnaamd',
                         'popnaame',
                         'popnaamf',
                         'popnaamg',
                         'popnaamh',
                         'popnaami',
                         'popnaamj',
                         'popnaamk',
                         'popnaaml',
                         'popnaamm',
                         'popnaamn',
                         'popnaamo',
                         'popnaamp',
                         'popnaamq',
                         'popnaamr',
                         'popnatuurlijkgrasland',
                         'popnederlandseachtergrond',
                         'popnederlandseachtergrondrelatief',
                         'popnietstedelijk',
                         'popnietwoningen',
                         'popnieuwbouwwoningen',
                         'popnieuwvormingen',
                         'popomgevingsadressendichtheid',
                         'popongehuwdouderdan',
                         'popongehuwdtot',
                         'popoudpapierenkarton',
                         'popounietcommercieledienstverleningbanen',
                         'popounietcommercieledienstverleningbanenrelatief',
                         'popoverigedoodsoorzaken',
                         'popoverighuishoudelijkafval',
                         'popoverignietwestersemigratieachtergrond',
                         'popoverignietwestersemigratieachtergrondrelatief',
                         'popoverigpluimvee',
                         'poppaardenenponys',
                         'popparticulierehuishoudensexclstudenten',
                         'popparticulierehuishoudensexclstudentengembestinkomen',
                         'popparticulierehuishoudensexclstudentengemgestandaardinkomen',
                         'popparticulierehuishoudensexclstudentenmediaaninkomen',
                         'poppercvoertuigenmetbromfietskenteken',
                         'poppersonenautos',
                         'poppersonenautosparticulieren',
                         'poppersonenautosparticulierenrelatief',
                         'poppersonenautosrelatief',
                         'popprovincialewegen',
                         'poprecreatieterreinopp',
                         'poprecreatieterreinperc',
                         'poprecreatieterreinperinwoner',
                         'poprijkswegen',
                         'poprucultuurrecreatieoverigediensten',
                         'poprundvee',
                         'popsaldovermeerderingwoningenrelatief',
                         'popschapen',
                         'popsemibebouwdterreinopp',
                         'popsemibebouwdterreinperc',
                         'popsemibebouwdterreinperinwoner',
                         'popslachteenden',
                         'popspeciaalbasisonderwijs',
                         'popspecialescholen',
                         'popsterfte',
                         'popsterfterelatief',
                         'popsterkstedelijk',
                         'popstikstofuitscheiding',
                         'popsuriname',
                         'popsurinamerelatief',
                         'poptextiel',
                         'poptijdelijkgrasland',
                         'poptotaalaantalbanen',
                         'poptotaalaantalparticulierehuishoudens',
                         'poptotaalhuishoudelijkafval',
                         'poptotaalmetmigratieachtergrond',
                         'poptotaalmetmigratieachtergrondrelatief',
                         'poptotaalnietwestersemigratieachtergrond',
                         'poptotaalnietwestersemigratieachtergrondrelatief',
                         'poptotalebevolking',
                         'poptotaledruk',
                         'poptotaleoppervlakte',
                         'poptotaleoppervlaktecultuurgrond',
                         'poptotaleweglengte',
                         'poptotdeaowleeftijd',
                         'poptuinbouwonderglas',
                         'poptuinbouwopengrond',
                         'popturkije',
                         'popturkijerelatief',
                         'poptypeeenoudergezingembestinkomen',
                         'poptypeeenoudergezingemgestandaardinkomen',
                         'poptypeeenoudergezinmediaaninkomen',
                         'poptypeeenpersoonshuishoudengembestinkomen',
                         'poptypeeenpersoonshuishoudengemgestandaardinkomen',
                         'poptypeeenpersoonshuishoudenmediaaninkomen',
                         'poptypepaarmetkinderengembestinkomen',
                         'poptypepaarmetkinderengemgestandaardinkomen',
                         'poptypepaarmetkinderenmediaaninkomen',
                         'poptypepaarzonderkindgembestinkomen',
                         'poptypepaarzonderkindgemgestandaardinkomen',
                         'poptypepaarzonderkindmediaaninkomen',
                         'popuitkeringsontvangerstotaalmediaaninkomen',
                         'popuitwendigedoodsoorzaken',
                         'popvanafdeaowleeftijd',
                         'popvarkens',
                         'popvastemest',
                         'popverhuismobiliteitrelatief',
                         'popverkeersterreinopp',
                         'popverkeersterreinperc',
                         'popverkeersterreinperinwoner',
                         'popverpakkingsglas',
                         'popvertreknaaranderegemeente',
                         'popverweduwdouderdan',
                         'popverweduwdtot',
                         'popvestiginguitanderegemeente',
                         'popvoertuigenmetbromfietskenteken',
                         'popvoormaligenederlandseantillenaruba',
                         'popvoormaligenederlandseantillenarubarelatief',
                         'popvoorraadop1januari',
                         'popvoortgezetonderwijs',
                         'popvoortgezetonderwijsdiploma',
                         'popvrouwen',
                         'popwajonguitkering',
                         'popwaouitkering',
                         'popwatertotaal',
                         'popweinigstedelijk',
                         'popwerkloosheid',
                         'popwestersemigratieachtergrond',
                         'popwestersemigratieachtergrondrelatief',
                         'popwetenschappelijkonderwijs',
                         'popwiauitkeringwgaregeling',
                         'popwijken',
                         'popwomasterdoctoraal',
                         'popwoningbeziteigenwoninggembestinkomen',
                         'popwoningbeziteigenwoninggemgestandaardinkomen',
                         'popwoningbeziteigenwoningmediaaninkomen',
                         'popwoningbezithuurwoninggembestinkomen',
                         'popwoningbezithuurwoninggemgestandaardinkomen',
                         'popwoningbezithuurwoningmediaaninkomen',
                         'popwoningdichtheid',
                         'popwoningen',
                         'popzeersterkstedelijk',
                         'popziektenvanademhalingsstelsel',
                         'popziektenvanhartenvaatstelsel',
                         'begraafplaatsrechten_gemeenteheffingeuroinwoner',
                         'precariobelasting_gemeenteheffingeuroinwoner',
                         'reinigingsrechten_en_afvalstoffenheffing_gemeenteheffingeuroinwoner',
                         'rioolheffing_gemeenteheffingeuroinwoner',
                         'secretarieleges_burgerzaken_gemeenteheffingeuroinwoner',
                         'toeristenbelasting_gemeenteheffingeuroinwoner',
                         'totaal_onroerendezaakbelasting_gemeenteheffingeuroinwoner',
                         'begraafplaatsrechten_gemeenteheffing1000euro',
                         'precariobelasting_gemeenteheffing1000euro',
                         'reinigingsrechten_en_afvalstoffenheffing_gemeenteheffing1000euro',
                         'rioolheffing_gemeenteheffing1000euro',
                         'secretarieleges_burgerzaken_gemeenteheffing1000euro',
                         'toeristenbelasting_gemeenteheffing1000euro',
                         'totaal_onroerendezaakbelasting_gemeenteheffing1000euro']
DICT_WMO_RELATIVELY_COLS_BOERENVERSTAND_MAIKEL = {
    'aantalinwoners': ['mannen',
                       'vrouwen',
                       'alleenstaande_mannen',
                       'alleenstaande_vrouwen',
                       'gescheiden',
                       'ongehuwd',
                       'ouder_in_eenouderhuishouden_vrouwen',
                       'ouder_in_eenouderhuishouden_mannen'],
    'huishoudenstotaal': ['eenpersoonshuishoudens',
                          'huishoudenszonderkinderen',
                          'huishoudensmetkinderen'],
    'poptotalebevolking': ['popaantalrestaurantsbinnen3km',
                           'popafstandtothuisartsenpraktijk',
                           'poparbeidsongeschiktheidtotaal',
                           'popbevolkingsdichtheid',
                           'popk65tot80jaarrelatieveleeftijdsgroep',
                           'popk80jaarofouderrelatieveleeftijdsgroep',
                           'popomgevingsadressendichtheid',
                           'popwerkloosheid'
                           'popzeersterkstedelijk',
                           'popsterkstedelijk',
                           'popmatigstedelijk',
                           'popweinigstedelijk',
                           'popnietstedelijk',
                           'poptotaleoppervlakte']}
LIST_WMO_GET_DATA_BOERENVERSTAND_MAIKEL = ['aantalinwoners',
                                           'gemiddeldehuishoudensgrootte',
                                           # 'gemiddeldinkomenperinwoner',
                                           'gescheiden',
                                           'verweduwd',
                                           'alleenstaande_mannen',
                                           'alleenstaande_vrouwen',
                                           'ouder_in_eenouderhuishouden_mannen',
                                           'ouder_in_eenouderhuishouden_vrouwen',
                                           'popaantalrestaurantsbinnen3km',
                                           'popafstandtothuisartsenpraktijk',
                                           'poparbeidsongeschiktheidtotaal',
                                           'popbevolkingsdichtheid',
                                           'popeenpersoonshuishoudensrelatief',
                                           'popk65tot80jaarrelatieveleeftijdsgroep',
                                           'popk80jaarofouderrelatieveleeftijdsgroep',
                                           'popomgevingsadressendichtheid',
                                           'poppersonenautosrelatief',
                                           'popwerkloosheid']
LIST_COLUMNSELECTOR_2_BOERENVERSTAND_MAIKEL = ['codering_regio', 'interval',
                                               'aantalinwoners',
                                               'gemiddeldehuishoudensgrootte',
                                               'gescheiden',
                                               'verweduwd',
                                               'alleenstaande_mannen',
                                               'alleenstaande_vrouwen',
                                               'ouder_in_eenouderhuishouden_mannen',
                                               'ouder_in_eenouderhuishouden_vrouwen',
                                               'popaantalrestaurantsbinnen3km',
                                               'popafstandtothuisartsenpraktijk',
                                               'poparbeidsongeschiktheidtotaal',
                                               'popbevolkingsdichtheid',
                                               'popeenpersoonshuishoudensrelatief',
                                               'popk65tot80jaarrelatieveleeftijdsgroep',
                                               'popk80jaarofouderrelatieveleeftijdsgroep',
                                               'popomgevingsadressendichtheid',
                                               'poppersonenautosrelatief',
                                               'popwerkloosheid',
                                               'relative_mannen',
                                               'relative_vrouwen',
                                               'relative_alleenstaande_mannen',
                                               'relative_alleenstaande_vrouwen',
                                               'relative_gescheiden',
                                               'relative_ongehuwd',
                                               'relative_ouder_in_eenouderhuishouden_vrouwen',
                                               'relative_ouder_in_eenouderhuishouden_mannen',
                                               'relative_eenpersoonshuishoudens',
                                               'relative_huishoudenszonderkinderen',
                                               'relative_huishoudensmetkinderen',
                                               'relative_popaantalrestaurantsbinnen3km',
                                               'relative_popafstandtothuisartsenpraktijk',
                                               'relative_poparbeidsongeschiktheidtotaal',
                                               'relative_popbevolkingsdichtheid',
                                               'relative_popk65tot80jaarrelatieveleeftijdsgroep',
                                               'relative_popk80jaarofouderrelatieveleeftijdsgroep',
                                               'relative_popomgevingsadressendichtheid',
                                               'relative_popsterkstedelijk',
                                               'relative_popmatigstedelijk',
                                               'relative_popweinigstedelijk',
                                               'relative_popnietstedelijk',
                                               'relative_poptotaleoppervlakte']
DICT_RELATIVELY_COL_WMO = {}
LIST_CUSTOMSCALER_COLS_WMO = []
DICT_RELATIVELY_COL_WIJK = {
    'aantalinwoners': ['percentagewmoclienten', 'mannen', 'vrouwen', 'k0tot15jaar', 'k15tot25jaar',
                       'k25tot45jaar', 'k45tot65jaar', 'k65jaarofouder', 'ongehuwd', 'gehuwd',
                       'gescheiden', 'verweduwd', 'westerstotaal', 'nietwesterstotaal', 'marokko',
                       'nederlandseantillenenaruba', 'suriname', 'turkije', 'overignietwesters',
                       'geboortetotaal', 'geboorterelatief', 'sterftetotaal', 'sterfterelatief',
                       'aantalinkomensontvangers', 'personenpersoortuitkeringbijstand',
                       'personenpersoortuitkeringao', 'personenpersoortuitkeringww',
                       'personenpersoortuitkeringaow'],
    'huishoudenstotaal': ['eenpersoonshuishoudens', 'huishoudenszonderkinderen',
                          'huishoudensmetkinderen'],
    'bedrijfsvestigingentotaal': ['alandbouwbosbouwenvisserij', 'bfnijverheidenenergie',
                                  'gihandelenhoreca', 'hjvervoerinformatieencommunicatie',
                                  'klfinancieledienstenonroerendgoed', 'mnzakelijkedienstverlening',
                                  'rucultuurrecreatieoverigediensten'],
    'personenautostotaal': ['personenautosbrandstofbenzine', 'personenautosoverigebrandstof'],
    'oppervlaktetotaal': ['oppervlakteland', 'oppervlaktewater']}
LIST_CUSTOMSCALER_COLS_WIJK = ['wmoclienten', 'aantalinwoners', 'huishoudenstotaal', 'gemiddeldehuishoudensgrootte',
                               'bevolkingsdichtheid', 'woningvoorraad', 'gemiddeldewoningwaarde',
                               'percentageeengezinswoning',
                               'percentagemeergezinswoning', 'percentagebewoond', 'percentageonbewoond', 'koopwoningen',
                               'huurwoningentotaal', 'inbezitwoningcorporatie', 'inbezitoverigeverhuurders',
                               'eigendomonbekend',
                               'bouwjaarvoor2000', 'bouwjaarvanaf2000', 'gemiddeldelektriciteitsverbruiktotaal',
                               'gemelectriciteitsverbruikappartement', 'gemelectriciteitsverbruiktussenwoning',
                               'gemelectriciteitsverbruikhoekwoning', 'gemelectriciteitsverbruiktweeondereenkapwoning',
                               'gemelectriciteitsverbruikvrijstaandewoning', 'gemelectriciteitsverbruikhuurwoning',
                               'gemelectriciteitsverbruikeigenwoning', 'gemiddeldaardgasverbruiktotaal',
                               'gemgasverbruikappartement',
                               'gemgasverbruiktussenwoning', 'gemgasverbruikhoekwoning',
                               'gemgasverbruiktweeondereenkapwoning',
                               'gemgasverbruikvrijstaandewoning', 'gemgasverbruikhuurwoning',
                               'gemgasverbruikeigenwoning',
                               'percentagewoningenmetstadsverwarming', 'gemiddeldinkomenperinkomensontvanger',
                               'gemiddeldinkomenperinwoner', 'k40personenmetlaagsteinkomen',
                               'k20personenmethoogsteinkomen',
                               'actieven1575jaar', 'k40huishoudensmetlaagsteinkomen', 'k20huishoudensmethoogsteinkomen',
                               'huishoudensmeteenlaaginkomen', 'huishonderofrondsociaalminimum',
                               'bedrijfsvestigingentotaal',
                               'personenautostotaal', 'motorfietsen', 'afstandtothuisartsenpraktijk',
                               'afstandtotgrotesupermarkt',
                               'afstandtotkinderdagverblijf', 'afstandtotschool', 'scholenbinnen3km',
                               'oppervlaktetotaal',
                               'matevanstedelijkheid', 'omgevingsadressendichtheid']
DICT_RELATIVELY_COL_HUISHOUDEN = {
    'aantalinwoners': ['alleenstaande_mannen', 'alleenstaande_totaal_mannen_en_vrouwen', 'alleenstaande_vrouwen',
                       'ouder_in_eenouderhuishouden_mannen', 'ouder_in_eenouderhuishouden_totaal_mannen_en_vrouwen',
                       'ouder_in_eenouderhuishouden_vrouwen', 'overig_lid_huishouden_mannen',
                       'overig_lid_huishouden_totaal_mannen_en_vrouwen', 'overig_lid_huishouden_vrouwen']}
LIST_CUSTOMSCALER_COLS_HUISHOUDEN = ['partner_in_paar,_geen_kind(eren)_mannen',
                                     'partner_in_paar,_geen_kind(eren)_totaal_mannen_en_vrouwen',
                                     'partner_in_paar,_geen_kind(eren)_vrouwen',
                                     'partner_in_paar_met_kind(eren)_mannen',
                                     'partner_in_paar_met_kind(eren)_totaal_mannen_en_vrouwen',
                                     'partner_in_paar_met_kind(eren)_vrouwen',
                                     'persoon_in_institutioneel_huishouden_mannen',
                                     'persoon_in_institutioneel_huishouden_totaal_mannen_en_vrouwen',
                                     'persoon_in_institutioneel_huishouden_vrouwen',
                                     'persoon_in_particulier_huishouden_mannen',
                                     'persoon_in_particulier_huishouden_totaal_mannen_en_vrouwen',
                                     'persoon_in_particulier_huishouden_vrouwen',
                                     'thuiswonend_kind_mannen', 'thuiswonend_kind_totaal_mannen_en_vrouwen',
                                     'thuiswonend_kind_vrouwen', 'totaal_personen_mannen',
                                     'totaal_personen_totaal_mannen_en_vrouwen',
                                     'totaal_personen_vrouwen']
DICT_RELATIVELY_COL_BEVOLKING = {
    'poptotalebevolking': ['popmannen', 'popvrouwen', 'popjongerdan5jaarleeftijdsgroep',
                           'popk5tot10jaarleeftijdsgroep', 'popk10tot15jaarleeftijdsgroep',
                           'popk15tot20jaarleeftijdsgroep', 'popk20tot25jaarleeftijdsgroep',
                           'popk25tot45jaarleeftijdsgroep', 'popk45tot65jaarleeftijdsgroep',
                           'popk65tot80jaarleeftijdsgroep', 'popk80jaarofouderleeftijdsgroep', 'popongehuwdtot',
                           'popgehuwdtot', 'popgescheidentot', 'popverweduwdtot', 'popinwoners15jaarofouder',
                           'popnederlandseachtergrond', 'poptotaalmetmigratieachtergrond',
                           'popwestersemigratieachtergrond', 'poptotaalnietwestersemigratieachtergrond',
                           'popmarokko', 'popvoormaligenederlandseantillenaruba', 'popsuriname', 'popturkije',
                           'popoverignietwestersemigratieachtergrond', 'popzeersterkstedelijk', 'popsterkstedelijk',
                           'popmatigstedelijk', 'popweinigstedelijk', 'popnietstedelijk', 'popgeboorte',
                           'popsterfte', 'popgeboorteoverschot', 'popnieuwvormingen',
                           'popziektenvanhartenvaatstelsel', 'popziektenvanademhalingsstelsel',
                           'popuitwendigedoodsoorzaken', 'popoverigedoodsoorzaken', 'popvestiginguitanderegemeente',
                           'popvertreknaaranderegemeente', 'popbinnenlandsmigratiesaldo',
                           'popbinnenlandsmigratiesaldorelatief', 'popverhuismobiliteitrelatief', 'popimmigratie',
                           'popemigratie', 'popmigratiesaldo', 'popinwonersop31december', 'popbevolkingsgroei',
                           'popgemiddeldaantalinwoners', 'popbasisonderwijs', 'popspeciaalbasisonderwijs',
                           'popspecialescholen', 'popvoortgezetonderwijs', 'popberoepsopleidendeleerweg',
                           'popberoepsbegeleidendeleerweg', 'pophogerberoepsonderwijs',
                           'popwetenschappelijkonderwijs', 'popvoortgezetonderwijsdiploma',
                           'popmiddelbaarberoepsonderwijs', 'pophogerberoepsonderwijsbachelor',
                           'popwomasterdoctoraal', 'poptotaalaantalbanen', 'popalandbouwbosbouwenvisserijbanen',
                           'popbfnijverheidenenergiebanen', 'popgncommercieledienstverleningbanen',
                           'popounietcommercieledienstverleningbanen',
                           'poptotaleoppervlaktecultuurgrond', 'popakkerbouw', 'poptuinbouwopengrond',
                           'poptuinbouwonderglas', 'popblijvendgrasland', 'popnatuurlijkgrasland',
                           'poptijdelijkgrasland', 'popgroenvoedergewassen', 'popstikstofuitscheiding',
                           'popfosfaatuitscheiding', 'popkaliuitscheiding', 'popdunnemest', 'popvastemest',
                           'poppersonenautos', 'poppersonenautosparticulieren', 'popbedrijfsmotorvoertuigen',
                           'popmotorfietsen', 'popvoertuigenmetbromfietskenteken', 'poptotaalhuishoudelijkafval',
                           'pophuishoudelijkrestafval', 'popgrofhuishoudelijkrestafval', 'popgftafval',
                           'popoudpapierenkarton', 'popverpakkingsglas', 'poptextiel', 'popkleinchemischafval',
                           'popoverighuishoudelijkafval', 'poptotaleoppervlakte', 'popland', 'popwatertotaal',
                           'popbinnenwater', 'popbuitenwater', 'popomgevingsadressendichtheid',
                           'popverkeersterreinopp', 'popbebouwdterreinopp', 'popsemibebouwdterreinopp',
                           'poprecreatieterreinopp', 'popagrarischterreinopp',
                           'popbosenopennatuurlijkterreinopp'],
    'poptotaledruk': ['popgroenedruk', 'popgrijzedruk'],
    'popinwoners15jaarofouder': ['popongehuwdouderdan14', 'popgehuwdouderdan14', 'popgescheidenouderdan14',
                                 'popverweduwdouderdan14'],
    'poptotaalaantalparticulierehuishoudens': ['popeenpersoonshuishoudens', 'pophuishoudenszonderkinderen',
                                               'pophuishoudensmetkinderen', 'popeenpersoonshuishoudensrelatief',
                                               'pophuishoudenszonderkinderenrelatief',
                                               'pophuishoudensmetkinderenrelatief',
                                               'popgemiddeldehuishoudensgrootte', 'popvoorraadop1januari',
                                               'popnieuwbouwwoningen', 'popsaldovermeerderingwoningenrelatief',
                                               'popwoningdichtheid', 'popkoopwoningen', 'pophuurwoningen',
                                               'popeigendomonbekend', 'popwoningen', 'popnietwoningen',
                                               'popgemiddeldewoningwaarde'],
    'popbedrijfsvestigingentotaal': ['popalandbouwbosbouwenvisserij', 'popbfnijverheidenenergie',
                                     'popgihandelenhoreca', 'pophjvervoerinformatieencommunicatie',
                                     'popklfinancieledienstenonroerendgoed', 'popmnzakelijkedienstverlening',
                                     'poprucultuurrecreatieoverigediensten'],
    'poptotaleweglengte': ['popgemeentelijkeenwaterschapswegen', 'popprovincialewegen', 'poprijkswegen']
}
LIST_CUSTOMSCALER_COLS_BEVOLKING = ['popjongerdan5jaarrelatieveleeftijdsgroep',
                                    'popk5tot10jaarrelatieveleeftijdsgroep',
                                    'popk10tot15jaarrelatieveleeftijdsgroep',
                                    'popk15tot20jaarrelatieveleeftijdsgroep',
                                    'popk20tot25jaarrelatieveleeftijdsgroep',
                                    'popk25tot45jaarrelatieveleeftijdsgroep',
                                    'popk45tot65jaarrelatieveleeftijdsgroep',
                                    'popk65tot80jaarrelatieveleeftijdsgroep',
                                    'popk80jaarofouderrelatieveleeftijdsgroep',
                                    'popnederlandseachtergrondrelatief', 'poptotaalmetmigratieachtergrondrelatief',
                                    'popwestersemigratieachtergrondrelatief',
                                    'poptotaalnietwestersemigratieachtergrondrelatief', 'popmarokkorelatief',
                                    'popvoormaligenederlandseantillenarubarelatief', 'popsurinamerelatief',
                                    'popturkijerelatief', 'popoverignietwestersemigratieachtergrondrelatief',
                                    'popbevolkingsdichtheid', 'popgeboorterelatief', 'popsterfterelatief',
                                    'popgeboorteoverschotrelatief', 'popmigratiesaldorelatief',
                                    'popbevolkingsgroeirelatief', 'popalandbouwbosbouwenvisserijbanenrelatief',
                                    'popbfnijverheidenenergiebanenrelatief',
                                    'popgncommercieledienstverleningbanenrelatief',
                                    'popounietcommercieledienstverleningbanenrelatief',
                                    'popparticulierehuishoudensexclstudenten',
                                    'popparticulierehuishoudensexclstudentengembestinkomen',
                                    'poptypeeenpersoonshuishoudengembestinkomen',
                                    'poptypeeenoudergezingembestinkomen', 'poptypepaarzonderkindgembestinkomen',
                                    'poptypepaarmetkinderengembestinkomen',
                                    'popbroninkomenalswerknemergembestinkomen',
                                    'popbroninkomenalszelfstandigegembestinkomen',
                                    'popbronoverdrachtsinkomengembestinkomen',
                                    'popwoningbeziteigenwoninggembestinkomen',
                                    'popwoningbezithuurwoninggembestinkomen',
                                    'popparticulierehuishoudensexclstudentengemgestandaardinkomen',
                                    'poptypeeenpersoonshuishoudengemgestandaardinkomen',
                                    'poptypeeenoudergezingemgestandaardinkomen',
                                    'poptypepaarzonderkindgemgestandaardinkomen',
                                    'poptypepaarmetkinderengemgestandaardinkomen',
                                    'popbroninkomenalswerknemergemgestandaardinkomen',
                                    'popbroninkomenalszelfstandigegemgestandaardinkomen',
                                    'popbronoverdrachtsinkomengemgestandaardinkomen',
                                    'popwoningbeziteigenwoninggemgestandaardinkomen',
                                    'popwoningbezithuurwoninggemgestandaardinkomen',
                                    'popparticulierehuishoudensexclstudentenmediaaninkomen',
                                    'poptypeeenpersoonshuishoudenmediaaninkomen',
                                    'poptypeeenoudergezinmediaaninkomen', 'poptypepaarzonderkindmediaaninkomen',
                                    'poptypepaarmetkinderenmediaaninkomen',
                                    'popbroninkomenalswerknemermediaaninkomen',
                                    'popbroninkomenalszelfstandigemediaaninkomen',
                                    'popbronoverdrachtsinkomenmediaaninkomen',
                                    'popwoningbeziteigenwoningmediaaninkomen',
                                    'popwoningbezithuurwoningmediaaninkomen',
                                    'popuitkeringsontvangerstotaalmediaaninkomen', 'poptotdeaowleeftijd',
                                    'popvanafdeaowleeftijd', 'popwerkloosheid',
                                    'popbijstandgerelateerdtotaowleeftijd', 'popbijstandgerelateerdvanafaowleeftijd',
                                    'popbijstandtotdeaowleeftijd', 'poparbeidsongeschiktheidtotaal',
                                    'popwaouitkering', 'popwiauitkeringwgaregeling', 'popwajonguitkering', 'popaow',
                                    'poppersonenautosrelatief', 'poppersonenautosparticulierenrelatief',
                                    'popmotorfietsenrelatief', 'poppercvoertuigenmetbromfietskenteken',
                                    'popafstandtothuisartsenpraktijk', 'popaantalhuisartsenpraktijkenbinnen3km',
                                    'popafstandtothuisartsenpost', 'popafstandtotziekenhuis',
                                    'popaantalziekenhuizenbinnen20km', 'popafstandtotkinderdagverblijf',
                                    'popaantalkinderdagverblijvenbinnen3km', 'popafstandtotschoolbasisonderwijs',
                                    'popaantalbasisonderwijsscholenbinnen3km', 'popafstandtotschoolvmbo',
                                    'popaantalscholenvmbobinnen5km', 'popafstandtotschoolhavovwo',
                                    'popaantalscholenhavovwobinnen5km', 'popafstandtotgrotesupermarkt',
                                    'popaantalgrotesupermarktenbinnen3km', 'popafstandtotrestaurant',
                                    'popaantalrestaurantsbinnen3km', 'popafstandtotbibliotheek',
                                    'popafstandtotbioscoop', 'popaantalbioscopenbinnen10km', 'popafstandtotzwembad',
                                    'popafstandtotsportterrein', 'popafstandtotopenbaargroen',
                                    'popafstandtotoprithoofdverkeersweg', 'popafstandtottreinstation',
                                    'popverkeersterreinperc', 'popbebouwdterreinperc',
                                    'popsemibebouwdterreinperc', 'poprecreatieterreinperc',
                                    'popagrarischterreinperc', 'popbosenopennatuurlijkterreinperc',
                                    'popverkeersterreinperinwoner', 'popbebouwdterreinperinwoner',
                                    'popsemibebouwdterreinperinwoner', 'poprecreatieterreinperinwoner',
                                    'popagrarischterreinperinwoner', 'popbosenopennatuurlijkterreinperinwoner',
                                    'poprundvee', 'popschapen', 'popgeiten',
                                    'poppaardenenponys', 'popvarkens', 'popkippen', 'popkalkoenen', 'popslachteenden',
                                    'popoverigpluimvee', 'popkonijnen', 'popedelpelsdieren']
DICT_RELATIVELY_COL_HEFFING = {}
LIST_CUSTOMSCALER_COLS_HEFFING = ['begraafplaatsrechten_gemeenteheffingeuroinwoner',
                                  'precariobelasting_gemeenteheffingeuroinwoner',
                                  'reinigingsrechten_en_afvalstoffenheffing_gemeenteheffingeuroinwoner',
                                  'rioolheffing_gemeenteheffingeuroinwoner',
                                  'secretarieleges_burgerzaken_gemeenteheffingeuroinwoner',
                                  'toeristenbelasting_gemeenteheffingeuroinwoner',
                                  'totaal_onroerendezaakbelasting_gemeenteheffingeuroinwoner',
                                  'begraafplaatsrechten_gemeenteheffing1000euro',
                                  'precariobelasting_gemeenteheffing1000euro',
                                  'reinigingsrechten_en_afvalstoffenheffing_gemeenteheffing1000euro',
                                  'rioolheffing_gemeenteheffing1000euro',
                                  'secretarieleges_burgerzaken_gemeenteheffing1000euro',
                                  'toeristenbelasting_gemeenteheffing1000euro',
                                  'totaal_onroerendezaakbelasting_gemeenteheffing1000euro']
